services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src