services:
  nestjs_api_prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - NODE_ENV=production
    volumes:
      - ./src:/usr/src/app/src