# Use Node.js 20 Alpine as the base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json files
# COPY package*.json ./
# Copy all application files
COPY . .

# Install dependencies
RUN npm install

RUN npm run build

RUN rm -rf ./src

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["npm", "run", "start:prod"]
